### ISSUE TITLE
Out of Memory when trying to parse 1 gb text file

### ISSUE THREAD

**Issue by AndyNewmanCRIBL** [paulsena/Cribl-Log-Collector-Interview#2]
when parsing a 1gb+ text file, the service crashes

**Comment by AndyNewmanCRIBL** [comment]
```
2024-02-13T10:15:28.268-07:00 ERROR 138083 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space] with root cause

java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringUTF16.compress(StringUTF16.java:161) ~[na:na]
	at java.base/java.lang.String.<init>(String.java:4768) ~[na:na]
	at java.base/java.lang.String.<init>(String.java:303) ~[na:na]
	at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:403) ~[na:na]
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:347) ~[na:na]
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:436) ~[na:na]
	at java.base/java.io.BufferedReader$1.hasNext(BufferedReader.java:681) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1949) ~[na:na]
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292) ~[na:na]
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda/0x00007f6d580e0bc0.getAsBoolean(Unknown Source) ~[na:na]
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[na:na]
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161) ~[na:na]
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298) ~[na:na]
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[na:na]
	at com.cribl.logcollector.services.CriblFileWatcher.readFileLinesInReverseWithStreams(CriblFileWatcher.java:74) ~[classes/:na]
	at com.cribl.logcollector.services.CriblFileWatcher.call(CriblFileWatcher.java:46) ~[classes/:na]
	at com.cribl.logcollector.services.CriblFileWatcher.call(CriblFileWatcher.java:21) ~[classes/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.runWith(Thread.java:1596) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

```

**Comment by paulsena** [comment]
Hey @AndyNewmanCRIBL , thanks for reviewing!

Let me take a look. Is your log file available online. How many entries are you querying for the tail?
I was testing with a 1.6 GB log file in my development and it is working without any OOM errors. Available here: https://github.com/logpai/loghub?tab=readme-ov-file
It's the HSDF_V1 sample Hadoop log file.

**Comment by paulsena** [comment]
I added extra validation around numEntries to tail to ensure a malicious user can't request an enormous amount of records and cause out of memory in the JVM, exception.
Defaults to max requestable of 100 now and configurable via props.

Also, just brainstorming possible problems with your test file. Does it have line breaks? Possibly if there are no carriage returns (CR or CR LF) then it might be trying to read the whole file as one line.

**Comment by paulsena** [comment]
Can't reproduce. Could you retest with my latest code when you have a chance?

**Comment by AndyNewmanCRIBL** [comment]
@paulsena with your latest changes, I can no longer search some of the lines in the files, but the 1gb file is searched instantaneously, which seems odd
![image](https://github.com/paulsena/Cribl-Log-Collector-Interview/assets/159371738/f9d24b0b-31fb-4667-bb82-eba289fe3a1f)

**Comment by paulsena** [comment]
@AndyNewmanCRIBL 

Thanks, made this new lower level byte implementation in a hurry yesterday so I don't hold up interview review and had an edge case bug where if files runs out before we hit our max lines, I needed to flush remaining characters in buffer to results list.

The multi GB file returning almost instantly is be design 😄 Reading using byte offsets I was seeing 2ms processing times to tail 10 tiles. 

Thank you!
